before review
channamakover/karate-kid-kickstart pull request #1
Opened 2022-02-08 09:06 UTC by channamakover

2022-02-08 11:43 UTC, tombenezra requested changes

2022-02-08 11:43 UTC, tombenezra commented on 1-Vanilla/index.html
> +    <header class="header">
unused? remove if so

2022-02-08 11:43 UTC, tombenezra commented on 1-Vanilla/index.html
> +        <div class="ul-container">
better not to name class with their corresponding html element

2022-02-08 11:43 UTC, tombenezra commented on 1-Vanilla/index.html
> +                <!-- <button class="button-style" id="add-button">add</button> -->
remove comments

2022-02-08 11:43 UTC, tombenezra commented on 1-Vanilla/styles.css
> +    height:100vm;
```suggestion
    height:100vh;
```

2022-02-08 11:43 UTC, tombenezra commented on 1-Vanilla/styles.css
> +body{
run formatter on this file

2022-02-08 12:52 UTC, ofirdagan requested changes

2022-02-08 12:52 UTC, ofirdagan commented on 1-Vanilla/index.html
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
what is this line. what does each param/value means

2022-02-08 12:52 UTC, ofirdagan commented on 1-Vanilla/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
what is this line. what does each param/value means

2022-02-08 12:52 UTC, ofirdagan commented on 1-Vanilla/index.html
> +    <title>Document</title>
u might want to give it a better title ;)

2022-02-08 12:52 UTC, ofirdagan commented on 1-Vanilla/toDoListApp.js
> +    buttonElement.addEventListener(eventType, () => {
I liked the fact that you took the logic of building a button element and put it together in a single function.
for each event there's the `event` param that your'e currently "throwing away".  make sure to integrate with it

2022-02-08 12:52 UTC, ofirdagan commented on 1-Vanilla/index.html
> +<!DOCTYPE html>
in general great PR! the code is very readable and the logic is split into small and reusable parts 👏
few functional / bugs I've noticed:

- make sure "enter" key also adds a new todo (not just clicking the button)
- Clear input after a new todo is added
- Uncheck don’t Clear the strike through
- The edit is not clear. You take what's currently in the input.. think of a better UX

2022-02-08 13:40 UTC, tombenezra approved these changes

2022-02-10 16:09 UTC, ofirdagan commented on 1-Vanilla/index.html
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
?

2022-02-10 16:09 UTC, ofirdagan commented on 1-Vanilla/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
?

2022-02-13 14:00 UTC, merged